ADMIN = "ADMIN"
DIRECTOR = "DIRECTOR"
MANAGER = "MANAGER"
CUSTOMER = "CUSTOMER"

USER_ROLES = (
    (ADMIN, ADMIN),
    (DIRECTOR, DIRECTOR),
    (MANAGER, MANAGER),
    (CUSTOMER, CUSTOMER),
)


NOT_ASSIGNED = 'NOT ASSIGNED'
PENDING = 'PENDING'
CANCELED = 'CANCELED'
DONE = 'DONE'

ORDER_STATUSES = (
    (NOT_ASSIGNED, NOT_ASSIGNED),
    (PENDING, PENDING),
    (DONE, DONE)
)
DONT_ENOUGH_MONEY = 'DONT ENOUGH MONEY'
MONEY_ENOUGH = 'MONEY ENOUGH'
AVAILABLE = 'AVAILABLE'
DONT_AVAILABLE = 'DONT AVALABLE'

'''
Main documents
'''
DOCUMENT_TEMPLATE_FILE_ALLOWED_EXTENSIONS = ('.docx', '.pdf', '.png', '.jpg', '.tiff')
# 10 MB
DOCUMENT_TEMPLATE_MAX_FILE_SIZE = 10485760

'''
Images
'''
IMAGE_ALLOWED_EXTENSIONS = ('.jpg', '.png')
# 10 MB
IMAGE_MAX_FILE_SIZE = 10485760